version: "3"
services: 
  nginx: 
    build: . 
    ports: 
      - "8080:80" 
    # This would create a local directory that serves as the volume source 
    # called 'mysite.template' which is connected to a directory of the 
    # same name inside 'conf.d/mysite.template' inside the container running nginx.
    volumes:  
    - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80 
      - PRODUCTION=true